export enum BaseUrls {
  ApplEn = 'https://www.investing.com/equities/apple-computer-inc-news',
  ApplTr = 'https://tr.investing.com/equities/apple-computer-inc-news',
  DowJonesEn = 'https://www.investing.com/indices/us-30-news',
  DowJonseTr = 'https://tr.investing.com/indices/us-30-news',
  EurUsdEn = 'https://www.investing.com/currencies/eur-usd-news',
  EurUsdTr = 'https://tr.investing.com/currencies/eur-usd-news',
  GbpUsdEn = 'https://www.investing.com/currencies/gbp-usd-news',
  GbpUsdTr = 'https://tr.investing.com/currencies/gbp-usd-news',
  UsdJpyEn = 'https://www.investing.com/currencies/usd-jpy-news',
  UsdJpyTr = 'https://tr.investing.com/currencies/usd-jpy-news',
  UsdChfEn = `https://www.investing.com/currencies/usd-chf-news`,
  UsdChfTr = 'https://tr.investing.com/currencies/usd-chf-news',
  AudUsdEn = 'https://www.investing.com/currencies/aud-usd-news',
  AudUsdTr = 'https://tr.investing.com/currencies/aud-usd-news',
  EurGbpEn = 'https://www.investing.com/currencies/eur-gbp-news',
  EurGbpTr = 'https://tr.investing.com/currencies/eur-gbp-news',
  UsdCadEn = 'https://www.investing.com/currencies/usd-cad-news',
  UsdCadTr = 'https://tr.investing.com/currencies/usd-cad-news',
  NzdUsdEn = 'https://www.investing.com/currencies/nzd-usd-news',
  NzdUsdTr = 'https://tr.investing.com/currencies/nzd-usd-news',
  XauUsdTr = 'https://tr.investing.com/currencies/xau-usd-news',
  XauUsdEn = 'https://www.investing.com/currencies/xau-usd-news',
  XagUsdEn = 'https://www.investing.com/currencies/xag-usd-news',
  XagUsdTr = 'https://tr.investing.com/currencies/xag-usd-news',
}
